name: formatting-check

on:
  push:
    # Only run on pushes to pull request branches
    branches-ignore:
      - 'master'
      - 'master-*'
  pull_request:

jobs:

  # Checking for correct formatting of branch for C code changes
  check-formatting:
    name: Formatting Check
    runs-on: ubuntu-18.04
    container: ubuntu:18.04
    steps:

      # Cache Rust stuff.
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry

      - name: Install dependencies
        run: |
          apt update
          apt -y install \
                libpcre3 \
                libpcre3-dev \
                build-essential \
                autoconf \
                automake \
                git \
                libtool \
                libpcap-dev \
                libnet1-dev \
                libyaml-0-2 \
                libyaml-dev \
                libcap-ng-dev \
                libcap-ng0 \
                libmagic-dev \
                libnetfilter-queue-dev \
                libnetfilter-queue1 \
                libnfnetlink-dev \
                libnfnetlink0 \
                libhiredis-dev \
                libjansson-dev \
                libpython2.7 \
                make \
                python \
                rustc \
                software-properties-common \
                wget \
                zlib1g \
                zlib1g-dev
      - name: Install packages for clang-format
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          # no need to install full clang using https://apt.llvm.org/llvm.sh
          # using clang 9
          add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
          apt-get update
          apt-get install -y clang-format-9
      - name: Install cbindgen
        run: cargo install --force --debug --version 0.14.1 cbindgen
      - run: echo "::add-path::$HOME/.cargo/bin"
      - uses: actions/checkout@v1
      - run: git clone https://github.com/OISF/libhtp -b 0.5.x
      - run: ./autogen.sh
      - run: ./configure --enable-unittests
      - name: Check formatting
        run: |
          if ! make diffstat-style-branch >> check_formatting_log.txt 2>&1; then
              echo "::warning ::Formatting is not following code style guide!"
              tail -n 50 check_formatting_log.txt
          else
              echo "Formatting is following code style guide"
          fi
